export const chefs = [
  {
    id: 1,
    author: 'Dina Burgyn',
    photo:
      'https://robohash.org/quaeratbeataevoluptas.png?size=160x160&set=set1',
    recipes: 4,
    followers: 83,
    following: 142,
    isFollow: false,
    bio: 'In congue. Etiam justo. Etiam pretium iaculis justo.',
  },
  {
    id: 2,
    author: 'Fidelio Oven',
    photo: 'https://robohash.org/illoquoquia.png?size=160x160&set=set1',
    recipes: 34,
    followers: 112,
    following: 39,
    isFollow: true,
    bio: 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
  },
  {
    id: 3,
    author: 'Tabby Champniss',
    photo: 'https://robohash.org/autvoluptasnon.png?size=160x160&set=set1',
    recipes: 37,
    followers: 143,
    following: 120,
    isFollow: true,
    bio: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',
  },
  {
    id: 4,
    author: 'Dunstan Arman',
    photo: 'https://robohash.org/veroanimiet.png?size=160x160&set=set1',
    recipes: 10,
    followers: 24,
    following: 52,
    isFollow: false,
    bio: 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
  },
  {
    id: 5,
    author: 'Claudell De La Haye',
    photo: 'https://robohash.org/totamrerummagni.png?size=160x160&set=set1',
    recipes: 16,
    followers: 34,
    following: 130,
    isFollow: true,
    bio: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',
  },
  {
    id: 6,
    author: 'Roz Galtone',
    photo: 'https://robohash.org/minusodioratione.png?size=160x160&set=set1',
    recipes: 9,
    followers: 95,
    following: 124,
    isFollow: false,
    bio: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.',
  },
  {
    id: 7,
    author: 'Olympe Ruegg',
    photo:
      'https://robohash.org/magnamarchitectoexplicabo.png?size=160x160&set=set1',
    recipes: 20,
    followers: 50,
    following: 35,
    isFollow: true,
    bio: 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
  },
  {
    id: 8,
    author: 'Annabal Eriksson',
    photo: 'https://robohash.org/utvelitlaborum.png?size=160x160&set=set1',
    recipes: 21,
    followers: 111,
    following: 16,
    isFollow: false,
    bio: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
  },
  {
    id: 9,
    author: 'Philbert Cino',
    photo:
      'https://robohash.org/molestiasvoluptasest.png?size=160x160&set=set1',
    recipes: 38,
    followers: 143,
    following: 39,
    isFollow: true,
    bio: 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
  },
  {
    id: 10,
    author: 'Alejoa Paskin',
    photo:
      'https://robohash.org/esseassumendatempora.png?size=160x160&set=set1',
    recipes: 15,
    followers: 56,
    following: 84,
    isFollow: false,
    bio: 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
  },
  {
    id: 11,
    author: 'Hadlee Bartolomivis',
    photo:
      'https://robohash.org/etconsequaturdoloremque.png?size=160x160&set=set1',
    recipes: 5,
    followers: 73,
    following: 47,
    isFollow: true,
    bio: 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
  },
  {
    id: 12,
    author: 'Aime Tommasetti',
    photo:
      'https://robohash.org/fugaassumendaconsequatur.png?size=160x160&set=set1',
    recipes: 38,
    followers: 121,
    following: 2,
    isFollow: false,
    bio: 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
  },
];
