export const detailedDishes = [
  {
    id: 1,
    author: 'Thedric Rapinett',
    title: 'Trichosurus vulpecula',
    time: 43,
    complexity: 3,
    likes: 23,
    isLiked: true,
    saves: 67,
    isSaved: false,
    description:
      'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.',
    ingredients: [5, 8, 5, 0],
    image: 'http://dummyimage.com/1700x796.png/cc0000/ffffff',
  },
  {
    id: 2,
    author: 'Nelly Benninck',
    title: 'Chlidonias leucopterus',
    time: 38,
    complexity: 1,
    likes: 60,
    isLiked: false,
    saves: 54,
    isSaved: false,
    description:
      'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
    ingredients: [5, 7, 8, 6],
    image: 'http://dummyimage.com/1310x899.png/ff4444/ffffff',
  },
  {
    id: 3,
    author: 'Englebert Ricks',
    title: 'Terathopius ecaudatus',
    time: 18,
    complexity: 2,
    likes: 68,
    isLiked: true,
    saves: 97,
    isSaved: false,
    description:
      'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
    ingredients: [7, 6, 1, 8],
    image: 'http://dummyimage.com/1725x806.png/dddddd/000000',
  },
  {
    id: 4,
    author: 'Baird Bartalucci',
    title: 'Eudyptula minor',
    time: 13,
    complexity: 2,
    likes: 3,
    isLiked: true,
    saves: 74,
    isSaved: true,
    description:
      'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    ingredients: [4, 9, 3, 4],
    image: 'http://dummyimage.com/1114x1046.png/5fa2dd/ffffff',
  },
  {
    id: 5,
    author: 'Karlotta Lorraway',
    title: 'Oreamnos americanus',
    time: 53,
    complexity: 3,
    likes: 11,
    isLiked: false,
    saves: 43,
    isSaved: false,
    description:
      'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    ingredients: [4, 4, 8, 4],
    image: 'http://dummyimage.com/1434x940.png/cc0000/ffffff',
  },
  {
    id: 6,
    author: 'Robbie Yakushkev',
    title: 'Alectura lathami',
    time: 53,
    complexity: 3,
    likes: 39,
    isLiked: true,
    saves: 5,
    isSaved: true,
    description:
      'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.',
    ingredients: [5, 0, 2, 6],
    image: 'http://dummyimage.com/1328x790.png/cc0000/ffffff',
  },
  {
    id: 7,
    author: 'Kimbell Stote',
    title: 'Anser caerulescens',
    time: 13,
    complexity: 2,
    likes: 90,
    isLiked: true,
    saves: 62,
    isSaved: false,
    description:
      'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',
    ingredients: [8, 3, 2, 6],
    image: 'http://dummyimage.com/1726x955.png/ff4444/ffffff',
  },
  {
    id: 8,
    author: 'Georgine Streeton',
    title: 'Arctogalidia trivirgata',
    time: 58,
    complexity: 1,
    likes: 28,
    isLiked: true,
    saves: 35,
    isSaved: false,
    description:
      'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
    ingredients: [5, 5, 9, 8],
    image: 'http://dummyimage.com/1664x779.png/cc0000/ffffff',
  },
  {
    id: 9,
    author: 'Maggee Paice',
    title: 'Macropus robustus',
    time: 14,
    complexity: 1,
    likes: 34,
    isLiked: true,
    saves: 10,
    isSaved: true,
    description:
      'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
    ingredients: [2, 2, 5, 0],
    image: 'http://dummyimage.com/1586x950.png/ff4444/ffffff',
  },
  {
    id: 10,
    author: 'Caressa Fidock',
    title: 'Cereopsis novaehollandiae',
    time: 35,
    complexity: 3,
    likes: 81,
    isLiked: true,
    saves: 7,
    isSaved: false,
    description:
      'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
    ingredients: [8, 9, 2, 3],
    image: 'http://dummyimage.com/1522x1022.png/cc0000/ffffff',
  },
  {
    id: 11,
    author: 'Darlene Macquire',
    title: 'Phascogale tapoatafa',
    time: 15,
    complexity: 3,
    likes: 99,
    isLiked: true,
    saves: 54,
    isSaved: false,
    description:
      'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
    ingredients: [7, 1, 5, 1],
    image: 'http://dummyimage.com/1905x857.png/dddddd/000000',
  },
  {
    id: 12,
    author: "Standford D'eath",
    title: 'Herpestes javanicus',
    time: 41,
    complexity: 2,
    likes: 61,
    isLiked: true,
    saves: 88,
    isSaved: false,
    description:
      'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
    ingredients: [1, 7, 9, 9],
    image: 'http://dummyimage.com/1454x1024.png/5fa2dd/ffffff',
  },
];
