export const array = [
  {
    id: 1,
    author: 'Dehlia Crother',
    image: 'http://dummyimage.com/308x209.png/5fa2dd/ffffff',
    title: 'Twinflower Sandwort',
    likes: 5,
    saves: 27,
    isLiked: false,
    isSaved: true,
  },
  {
    id: 2,
    author: 'Napoleon Elsdon',
    image: 'http://dummyimage.com/308x209.png/ff4444/ffffff',
    title: 'Western Bladderpod',
    likes: 6,
    saves: 19,
    isLiked: true,
    isSaved: true,
  },
  {
    id: 3,
    author: 'Lishe Pohl',
    image: 'http://dummyimage.com/308x209.png/dddddd/000000',
    title: 'Fringed Brome',
    likes: 79,
    saves: 17,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 4,
    author: 'Tuckie Babbidge',
    image: 'http://dummyimage.com/308x209.png/cc0000/ffffff',
    title: 'Western Buttercup',
    likes: 30,
    saves: 39,
    isLiked: true,
    isSaved: false,
  },
  {
    id: 5,
    author: 'Neron Caldicott',
    image: 'http://dummyimage.com/308x209.png/5fa2dd/ffffff',
    title: 'Pseudoleskea Moss',
    likes: 94,
    saves: 17,
    isLiked: true,
    isSaved: true,
  },
  {
    id: 6,
    author: 'Mycah Antonucci',
    image: 'http://dummyimage.com/308x209.png/5fa2dd/ffffff',
    title: 'Cucumber Tree',
    likes: 78,
    saves: 40,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 7,
    author: 'Roxanne Chasemoore',
    image: 'http://dummyimage.com/308x209.png/dddddd/000000',
    title: 'West Indian Nightshade',
    likes: 55,
    saves: 19,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 8,
    author: 'Aldridge Thurston',
    image: 'http://dummyimage.com/308x209.png/5fa2dd/ffffff',
    title: 'Mourning Milkvetch',
    likes: 29,
    saves: 29,
    isLiked: false,
    isSaved: true,
  },
  {
    id: 9,
    author: 'Arni Tydeman',
    image: 'http://dummyimage.com/308x209.png/cc0000/ffffff',
    title: 'Horehound',
    likes: 80,
    saves: 88,
    isLiked: true,
    isSaved: false,
  },
  {
    id: 10,
    author: 'Johny Fairbrother',
    image: 'http://dummyimage.com/308x209.png/cc0000/ffffff',
    title: 'Glechoma',
    likes: 47,
    saves: 96,
    isLiked: false,
    isSaved: true,
  },
  {
    id: 11,
    author: 'Sheff Ulyet',
    image: 'http://dummyimage.com/308x209.png/cc0000/ffffff',
    title: "Moran's Manzanita",
    likes: 22,
    saves: 52,
    isLiked: false,
    isSaved: true,
  },
  {
    id: 12,
    author: 'Troy Pymer',
    image: 'http://dummyimage.com/308x209.png/cc0000/ffffff',
    title: "Clokey's Catchfly",
    likes: 66,
    saves: 2,
    isLiked: false,
    isSaved: true,
  },
];
